### DISCUSSION TITLE
Anleitung: Setting "Hyphenate CSS-Regeln einsetzen"

### DISCUSSION THREAD

**Discussion by GHSVS-de** [GHSVS-de/plg_system_hyphenateghsvs_slim#6] [Docs]
English: https://github.com/GHSVS-de/plg_system_hyphenateghsvs_slim/discussions/7

CSS-Regeln automatisch laden, die sich darum kümmern, dass definierte Selektoren auch in Browsern ihre Aufgabe erfüllen, die eh schon hyphens unterstützen.

Dieses Plugin fügt den Elementen, die Sie in den Feldern "[Hyphenate-Selektoren](https://github.com/GHSVS-de/plg_system_hyphenateghsvs_slim/discussions/3)" oder "[Stopp-Hyphenate-Selektoren](https://github.com/GHSVS-de/plg_system_hyphenateghsvs_slim/discussions/5)" konfiguriert haben, immer die CSS-Klassen `hyphenate` und `donthypenate` hinzu.

Browser (wie FireFox), die schlau genug sind, ohne zusätzliche Skripte zu trennen, benötigen dennoch die folgenden CSS-Zeilen. 

```css
.hyphenate{
 word-wrap: break-word;
 -webkit-hyphens: auto;
 -moz-hyphens: auto;
 -ms-hyphens: auto;
 -o-hyphens: auto;
 hyphens: auto;
}

.donthyphenate{
 word-wrap: break-word;
 -webkit-hyphens: none;
 -moz-hyphens: none;
 -ms-hyphens: none;
 -o-hyphens: none;
 hyphens: none;
}
```

Sie können sie in Ihren CSS-Dateien selbst hinzufügen oder einfach `JA` auswählen, um sie automatisch zu laden.

Wenn man sich darauf verlässt, dass alle populären Browser der Seitenbesucher silbentrennung sowieso beherrschen, kann man auf die Konfiguration von Sprachen gänzlich verzichten und spart so ein wenig Ressourcen.
