### DISCUSSION TITLE
Manual: Setting "Add hyphenate CSS rules"

### DISCUSSION THREAD

**Discussion by GHSVS-de** [GHSVS-de/plg_system_hyphenateghsvs_slim#7] [Docs]
Deutsch: https://github.com/GHSVS-de/plg_system_hyphenateghsvs_slim/discussions/6

This plugin adds always the CSS classes "`hyphenate`" and "`donthypenate`" to the elements that you've configured in fields "[Hyphenate-Selectors](https://github.com/GHSVS-de/plg_system_hyphenateghsvs_slim/discussions/2)" or "[Do-Not-Hyphenate-Selectors](https://github.com/GHSVS-de/plg_system_hyphenateghsvs_slim/discussions/4)".

Browsers (like FireFox) that are smart enough to hyphenate without additional scripts still need the following CSS lines.

```css
.hyphenate{
 word-wrap: break-word;
 -webkit-hyphens: auto;
 -moz-hyphens: auto;
 -ms-hyphens: auto;
 -o-hyphens: auto;
 hyphens: auto;
}

.donthyphenate{
 word-wrap: break-word;
 -webkit-hyphens: none;
 -moz-hyphens: none;
 -ms-hyphens: none;
 -o-hyphens: none;
 hyphens: none;
}
```

You can add them in your CSS files yourself or just select `YES` here to load them automatically.

If you have no idea what I'm talking about then setting `YES` is recommended.
